// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
)

// FakeNodeBGPStatuses implements NodeBGPStatusInterface
type FakeNodeBGPStatuses struct {
	Fake *FakeProjectcalicoV3
}

var nodebgpstatusesResource = schema.GroupVersionResource{Group: "projectcalico.org", Version: "v3", Resource: "nodebgpstatuses"}

var nodebgpstatusesKind = schema.GroupVersionKind{Group: "projectcalico.org", Version: "v3", Kind: "NodeBGPStatus"}

// Get takes name of the nodeBGPStatus, and returns the corresponding nodeBGPStatus object, and an error if there is any.
func (c *FakeNodeBGPStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v3.NodeBGPStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nodebgpstatusesResource, name), &v3.NodeBGPStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodeBGPStatus), err
}

// List takes label and field selectors, and returns the list of NodeBGPStatuses that match those selectors.
func (c *FakeNodeBGPStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v3.NodeBGPStatusList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nodebgpstatusesResource, nodebgpstatusesKind, opts), &v3.NodeBGPStatusList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v3.NodeBGPStatusList{ListMeta: obj.(*v3.NodeBGPStatusList).ListMeta}
	for _, item := range obj.(*v3.NodeBGPStatusList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeBGPStatuses.
func (c *FakeNodeBGPStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nodebgpstatusesResource, opts))
}

// Create takes the representation of a nodeBGPStatus and creates it.  Returns the server's representation of the nodeBGPStatus, and an error, if there is any.
func (c *FakeNodeBGPStatuses) Create(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.CreateOptions) (result *v3.NodeBGPStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nodebgpstatusesResource, nodeBGPStatus), &v3.NodeBGPStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodeBGPStatus), err
}

// Update takes the representation of a nodeBGPStatus and updates it. Returns the server's representation of the nodeBGPStatus, and an error, if there is any.
func (c *FakeNodeBGPStatuses) Update(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.UpdateOptions) (result *v3.NodeBGPStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nodebgpstatusesResource, nodeBGPStatus), &v3.NodeBGPStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodeBGPStatus), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeBGPStatuses) UpdateStatus(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.UpdateOptions) (*v3.NodeBGPStatus, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(nodebgpstatusesResource, "status", nodeBGPStatus), &v3.NodeBGPStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodeBGPStatus), err
}

// Delete takes name of the nodeBGPStatus and deletes it. Returns an error if one occurs.
func (c *FakeNodeBGPStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(nodebgpstatusesResource, name), &v3.NodeBGPStatus{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeBGPStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nodebgpstatusesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v3.NodeBGPStatusList{})
	return err
}

// Patch applies the patch and returns the patched nodeBGPStatus.
func (c *FakeNodeBGPStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.NodeBGPStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nodebgpstatusesResource, name, pt, data, subresources...), &v3.NodeBGPStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodeBGPStatus), err
}
