// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
)

// FakeIPAMBlocks implements IPAMBlockInterface
type FakeIPAMBlocks struct {
	Fake *FakeProjectcalicoV3
	ns   string
}

var ipamblocksResource = schema.GroupVersionResource{Group: "projectcalico.org", Version: "v3", Resource: "ipamblocks"}

var ipamblocksKind = schema.GroupVersionKind{Group: "projectcalico.org", Version: "v3", Kind: "IPAMBlock"}

// Get takes name of the iPAMBlock, and returns the corresponding iPAMBlock object, and an error if there is any.
func (c *FakeIPAMBlocks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v3.IPAMBlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipamblocksResource, c.ns, name), &v3.IPAMBlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.IPAMBlock), err
}

// List takes label and field selectors, and returns the list of IPAMBlocks that match those selectors.
func (c *FakeIPAMBlocks) List(ctx context.Context, opts v1.ListOptions) (result *v3.IPAMBlockList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipamblocksResource, ipamblocksKind, c.ns, opts), &v3.IPAMBlockList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v3.IPAMBlockList{ListMeta: obj.(*v3.IPAMBlockList).ListMeta}
	for _, item := range obj.(*v3.IPAMBlockList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iPAMBlocks.
func (c *FakeIPAMBlocks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipamblocksResource, c.ns, opts))

}

// Create takes the representation of a iPAMBlock and creates it.  Returns the server's representation of the iPAMBlock, and an error, if there is any.
func (c *FakeIPAMBlocks) Create(ctx context.Context, iPAMBlock *v3.IPAMBlock, opts v1.CreateOptions) (result *v3.IPAMBlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipamblocksResource, c.ns, iPAMBlock), &v3.IPAMBlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.IPAMBlock), err
}

// Update takes the representation of a iPAMBlock and updates it. Returns the server's representation of the iPAMBlock, and an error, if there is any.
func (c *FakeIPAMBlocks) Update(ctx context.Context, iPAMBlock *v3.IPAMBlock, opts v1.UpdateOptions) (result *v3.IPAMBlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipamblocksResource, c.ns, iPAMBlock), &v3.IPAMBlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.IPAMBlock), err
}

// Delete takes name of the iPAMBlock and deletes it. Returns an error if one occurs.
func (c *FakeIPAMBlocks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ipamblocksResource, c.ns, name), &v3.IPAMBlock{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIPAMBlocks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipamblocksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v3.IPAMBlockList{})
	return err
}

// Patch applies the patch and returns the patched iPAMBlock.
func (c *FakeIPAMBlocks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.IPAMBlock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipamblocksResource, c.ns, name, pt, data, subresources...), &v3.IPAMBlock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.IPAMBlock), err
}
