// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	scheme "github.com/projectcalico/api/pkg/client/clientset_generated/clientset/scheme"
)

// IPAMBlocksGetter has a method to return a IPAMBlockInterface.
// A group's client should implement this interface.
type IPAMBlocksGetter interface {
	IPAMBlocks(namespace string) IPAMBlockInterface
}

// IPAMBlockInterface has methods to work with IPAMBlock resources.
type IPAMBlockInterface interface {
	Create(ctx context.Context, iPAMBlock *v3.IPAMBlock, opts v1.CreateOptions) (*v3.IPAMBlock, error)
	Update(ctx context.Context, iPAMBlock *v3.IPAMBlock, opts v1.UpdateOptions) (*v3.IPAMBlock, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v3.IPAMBlock, error)
	List(ctx context.Context, opts v1.ListOptions) (*v3.IPAMBlockList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.IPAMBlock, err error)
	IPAMBlockExpansion
}

// iPAMBlocks implements IPAMBlockInterface
type iPAMBlocks struct {
	client rest.Interface
	ns     string
}

// newIPAMBlocks returns a IPAMBlocks
func newIPAMBlocks(c *ProjectcalicoV3Client, namespace string) *iPAMBlocks {
	return &iPAMBlocks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iPAMBlock, and returns the corresponding iPAMBlock object, and an error if there is any.
func (c *iPAMBlocks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v3.IPAMBlock, err error) {
	result = &v3.IPAMBlock{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipamblocks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IPAMBlocks that match those selectors.
func (c *iPAMBlocks) List(ctx context.Context, opts v1.ListOptions) (result *v3.IPAMBlockList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v3.IPAMBlockList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipamblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iPAMBlocks.
func (c *iPAMBlocks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ipamblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a iPAMBlock and creates it.  Returns the server's representation of the iPAMBlock, and an error, if there is any.
func (c *iPAMBlocks) Create(ctx context.Context, iPAMBlock *v3.IPAMBlock, opts v1.CreateOptions) (result *v3.IPAMBlock, err error) {
	result = &v3.IPAMBlock{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ipamblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(iPAMBlock).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a iPAMBlock and updates it. Returns the server's representation of the iPAMBlock, and an error, if there is any.
func (c *iPAMBlocks) Update(ctx context.Context, iPAMBlock *v3.IPAMBlock, opts v1.UpdateOptions) (result *v3.IPAMBlock, err error) {
	result = &v3.IPAMBlock{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ipamblocks").
		Name(iPAMBlock.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(iPAMBlock).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the iPAMBlock and deletes it. Returns an error if one occurs.
func (c *iPAMBlocks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipamblocks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iPAMBlocks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipamblocks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched iPAMBlock.
func (c *iPAMBlocks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.IPAMBlock, err error) {
	result = &v3.IPAMBlock{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ipamblocks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
