// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	scheme "github.com/projectcalico/api/pkg/client/clientset_generated/clientset/scheme"
)

// NodeBGPStatusesGetter has a method to return a NodeBGPStatusInterface.
// A group's client should implement this interface.
type NodeBGPStatusesGetter interface {
	NodeBGPStatuses() NodeBGPStatusInterface
}

// NodeBGPStatusInterface has methods to work with NodeBGPStatus resources.
type NodeBGPStatusInterface interface {
	Create(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.CreateOptions) (*v3.NodeBGPStatus, error)
	Update(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.UpdateOptions) (*v3.NodeBGPStatus, error)
	UpdateStatus(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.UpdateOptions) (*v3.NodeBGPStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v3.NodeBGPStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*v3.NodeBGPStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.NodeBGPStatus, err error)
	NodeBGPStatusExpansion
}

// nodeBGPStatuses implements NodeBGPStatusInterface
type nodeBGPStatuses struct {
	client rest.Interface
}

// newNodeBGPStatuses returns a NodeBGPStatuses
func newNodeBGPStatuses(c *ProjectcalicoV3Client) *nodeBGPStatuses {
	return &nodeBGPStatuses{
		client: c.RESTClient(),
	}
}

// Get takes name of the nodeBGPStatus, and returns the corresponding nodeBGPStatus object, and an error if there is any.
func (c *nodeBGPStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v3.NodeBGPStatus, err error) {
	result = &v3.NodeBGPStatus{}
	err = c.client.Get().
		Resource("nodebgpstatuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeBGPStatuses that match those selectors.
func (c *nodeBGPStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v3.NodeBGPStatusList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v3.NodeBGPStatusList{}
	err = c.client.Get().
		Resource("nodebgpstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeBGPStatuses.
func (c *nodeBGPStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("nodebgpstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeBGPStatus and creates it.  Returns the server's representation of the nodeBGPStatus, and an error, if there is any.
func (c *nodeBGPStatuses) Create(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.CreateOptions) (result *v3.NodeBGPStatus, err error) {
	result = &v3.NodeBGPStatus{}
	err = c.client.Post().
		Resource("nodebgpstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeBGPStatus).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeBGPStatus and updates it. Returns the server's representation of the nodeBGPStatus, and an error, if there is any.
func (c *nodeBGPStatuses) Update(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.UpdateOptions) (result *v3.NodeBGPStatus, err error) {
	result = &v3.NodeBGPStatus{}
	err = c.client.Put().
		Resource("nodebgpstatuses").
		Name(nodeBGPStatus.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeBGPStatus).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nodeBGPStatuses) UpdateStatus(ctx context.Context, nodeBGPStatus *v3.NodeBGPStatus, opts v1.UpdateOptions) (result *v3.NodeBGPStatus, err error) {
	result = &v3.NodeBGPStatus{}
	err = c.client.Put().
		Resource("nodebgpstatuses").
		Name(nodeBGPStatus.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeBGPStatus).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeBGPStatus and deletes it. Returns an error if one occurs.
func (c *nodeBGPStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("nodebgpstatuses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeBGPStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("nodebgpstatuses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeBGPStatus.
func (c *nodeBGPStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v3.NodeBGPStatus, err error) {
	result = &v3.NodeBGPStatus{}
	err = c.client.Patch(pt).
		Resource("nodebgpstatuses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
