// Copyright (c) 2021 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
)

// NodeBGPStatusLister helps list NodeBGPStatuses.
// All objects returned here must be treated as read-only.
type NodeBGPStatusLister interface {
	// List lists all NodeBGPStatuses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v3.NodeBGPStatus, err error)
	// Get retrieves the NodeBGPStatus from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v3.NodeBGPStatus, error)
	NodeBGPStatusListerExpansion
}

// nodeBGPStatusLister implements the NodeBGPStatusLister interface.
type nodeBGPStatusLister struct {
	indexer cache.Indexer
}

// NewNodeBGPStatusLister returns a new NodeBGPStatusLister.
func NewNodeBGPStatusLister(indexer cache.Indexer) NodeBGPStatusLister {
	return &nodeBGPStatusLister{indexer: indexer}
}

// List lists all NodeBGPStatuses in the indexer.
func (s *nodeBGPStatusLister) List(selector labels.Selector) (ret []*v3.NodeBGPStatus, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v3.NodeBGPStatus))
	})
	return ret, err
}

// Get retrieves the NodeBGPStatus from the index for a given name.
func (s *nodeBGPStatusLister) Get(name string) (*v3.NodeBGPStatus, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v3.Resource("nodebgpstatus"), name)
	}
	return obj.(*v3.NodeBGPStatus), nil
}
